# Generated by Django 4.1 on 2022-08-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='sizeoption',
        ),
        migrations.DeleteModel(
            name='SizeOption',
        ),
    ]
