# Generated by Django 4.1 on 2022-09-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_smtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images4',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
